server:
  port: 6969
#  session:
#    cookie:
#      name: SSID
#  tomcat:
#    remote-ip-header: X-Forwarded-For
#    protocol-header: X-Forwarded-Proto
#  compression:
#    enabled: true
#    mime-types: application/x-java-serialized-object,application/json,application/xml,text/html,text/xml,text/plain
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jianboke?autoReconnect=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    validation-query: SELECT 1
    test-on-borrow: true
logging:
  file: target/jianboke.log
  level:
    com.jianboke: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
    liquibase: WARN
app:
  work:
    directory: target/work
  security:
    key: 8a70f2e95f2f5184495a979a4e624a9e6e9ea821
data:
  imgConfig:
    baseUrl: E:\idea_workspace\jianboke-dev\jianboke\src\main\resources\static
    mdImgRootPath: http://localhost:6969/
  email:
    host: smtp.aliyun.com
    sender: jianboke@aliyun.com
    nickname: 简博客
    username: jianboke@aliyun.com
    password: jianboke,0919
    subject:
    receiver:
    message:
    #密钥过期时间，暂定30分钟
    expireTime: 30

